package com.xingfugo.business.outapi.airline.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CreateOrderByPassengerServiceImpl_1_0Service service = new CreateOrderByPassengerServiceImpl_1_0Service();
 * CreateOrderByPassengerService10 portType = service.getCreateOrderByPassengerServiceImpl10Port();
 * portType.createOrderByPassenger(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CreateOrderByPassengerServiceImpl_1_0Service", targetNamespace = "http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/", wsdlLocation = "http://ws.tongyedns.com:8000//ltips/services/createOrderByPassengerService1.0?wsdl")
public class CreateOrderByPassengerServiceImpl10Service extends Service {

	private final static URL CREATEORDERBYPASSENGERSERVICEIMPL10SERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(CreateOrderByPassengerServiceImpl10Service.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = CreateOrderByPassengerServiceImpl10Service.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"http://ws.tongyedns.com:8000//ltips/services/createOrderByPassengerService1.0?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://ws.tongyedns.com:8000//ltips/services/createOrderByPassengerService1.0?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CREATEORDERBYPASSENGERSERVICEIMPL10SERVICE_WSDL_LOCATION = url;
	}

	public CreateOrderByPassengerServiceImpl10Service(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CreateOrderByPassengerServiceImpl10Service() {
		super(
				CREATEORDERBYPASSENGERSERVICEIMPL10SERVICE_WSDL_LOCATION,
				new QName(
						"http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/",
						"CreateOrderByPassengerServiceImpl_1_0Service"));
	}

	/**
	 * 
	 * @return returns CreateOrderByPassengerService10
	 */
	@WebEndpoint(name = "CreateOrderByPassengerServiceImpl_1_0Port")
	public CreateOrderByPassengerService10 getCreateOrderByPassengerServiceImpl10Port() {
		return super
				.getPort(
						new QName(
								"http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/",
								"CreateOrderByPassengerServiceImpl_1_0Port"),
						CreateOrderByPassengerService10.class);
	}

}
