package com.xingfugo.business.outapi.airline.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CreateOrderByPassengerService_1_0", targetNamespace = "http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/")
public interface CreateOrderByPassengerService10 {

	/**
	 * 
	 * @param request
	 * @return returns
	 *         com.xingfugo.business.outapi.airline.webservice.CreateOrderByPassengerReply
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "createOrderByPassenger", targetNamespace = "http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/", className = "com.xingfugo.business.outapi.airline.webservice.CreateOrderByPassenger")
	@ResponseWrapper(localName = "createOrderByPassengerResponse", targetNamespace = "http://createorderbypassenger.b2b.service.version1_0.webservice.model.ltips.com/", className = "com.xingfugo.business.outapi.airline.webservice.CreateOrderByPassengerResponse")
	public CreateOrderByPassengerReply createOrderByPassenger(
			@WebParam(name = "request", targetNamespace = "")
			CreateOrderByPassengerRequest request);

}
